//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAutoComplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public string AlumnoId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Pass { get; set; }
        public string Key { get; set; }
        public bool EsSabatino { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    }
}
